- name: BackEnd 
  hosts: all
  become: yes
  tasks:
     - name: install nodejs
       ansible.builtin.yum:
          name: nodejs
          state: installed
          
     - name: Check node-js Version
       ansible.builtin.shell: node --version
      
  
      
