- name: BackEnd 
  hosts: all
  become: yes
  tasks:
     - name: install nodejs
       ansible.builtin.shell: dnf module insytall nodejs:20
          
         
     - name: Get Node.js version
       shell: node --version
       register: node_version_output

     - debug:
        msg: "Node.js version is {{ node_version_output.stdout }}"
      
  
      
