- name: BackEnd 
  hosts: all
  become: yes
  tasks:
     - name: install nodejs
       ansible.builtin.yum:
          name: nodejs
          state: installed
          
     - name: Get Node.js version
       shell: node --version
       register: node_version_output

    - debug:
        msg: "Node.js version is {{ node_version_output.stdout }}"
      
  
      
