- name: BackEnd 
  hosts: all
  become: yes
  tasks:
     - name: install nodejs
       shell: dnf module install nodejs:20 -y
          
     - name: Get Node.js version
       shell: node --version
       register: node_version_output
     - debug:
        msg: "Node.js version is {{ node_version_output.stdout }}"

     - name: Create Directory
       ansible.builtin.file:
          path: /app
          state: directory
          
     - name: Craete Expense Application user
       ansible.builtin.user: 
         name: expense

     - name: Downlaod zip file
       ansible.builtin.get_url:
          url: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
          dest: /tmp

     - name: Extract File Data
       ansible.builtin.unarchive:
          src: /tmp/expense-backend-v2.zip
          dest: /app
          remote_src: yes

     - name: download Npdejs dependencies
       ansible.builtin.shell: npm install
       args:
          chdir: /app

     - name: Copy files
       ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service
       
       
       
     
  
      
