- name: BackEnd 
  hosts: all
  become: yes
  tasks:
     - name: install nodejs
       ansible.builtin.yum:
          name: nodejs
          state: installed

     - name: Start NodeJS
       ansible.builtin.service:
           name: nodejs
           state: started
       
      
