- name: Front End Setup
  hosts: all
  become: true
  tasks:
    - name: Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: Start Nginx
      ansible.builtin.service:
          name: nginx
          state: started

    - name: Remove Nginx File
      ansible.builtin.file:
          path: /usr/share/nginx/html
          state: absent

    - name: Create new directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download file
      ansible.builtin.get_url:
            url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip 
            dest: /tmp/

    - name: Extrat Content
      ansible.builtin.unarchive:
          src: /tmp/expense-frontend-v2.zip
          dest: /usr/share/nginx/html/
          remote_src: yes
          

        
          
       
