- name: Front End Setup
  hosts: all
  become: true
  tasks:
    - name: Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: Start Nginx
      ansible.builtin.service:
          name: nginx
          state: started
